spring:
  resources:
    staticLocations: classpath:/static
    #staticLocations: classpath:/cliente/src,classpath:/cliente/node_modules,classpath:/cliente/dist
  datasource:
    url: jdbc:mysql://192.168.1.37:3306/oposiciones?useSSL=false
    username: oposiciones
    password: mozondiga
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        hbm2ddl:
          auto: create
